const players = [
  {
    name: "Aaron Ramsdale",
    code: 1001,
    positionId: 1,
    teamId: 1,
    points: 179,
  },
  {
    name: "Runar Alex Runarsson",
    code: 1002,
    positionId: 1,
    teamId: 1,
    points: 0,
  },
  {
    name: "Matt Turner",
    code: 1003,
    positionId: 1,
    teamId: 1,
    points: 39,
  },
  {
    name: "Karl Hein",
    code: 1004,
    positionId: 1,
    teamId: 1,
    points: -1,
  },
  {
    name: "Gabriel dos Santos Magalhaes",
    code: 2001,
    positionId: 3,
    teamId: 1,
    points: 177,
  },
  {
    name: "Rob Holding",
    code: 2002,
    positionId: 3,
    teamId: 1,
    points: 67,
  },
  {
    name: "Pablo Mari",
    code: 2003,
    positionId: 3,
    teamId: 1,
    points: 0,
  },
  {
    name: "Kieran Tierney",
    code: 2004,
    positionId: 3,
    teamId: 1,
    points: 83,
  },
  {
    name: "Nuno Tavares",
    code: 2005,
    positionId: 3,
    teamId: 1,
    points: 0,
  },
  {
    name: "Ben White",
    code: 2006,
    positionId: 3,
    teamId: 1,
    points: 180,
  },
  {
    name: "Takehiro Tomiyasu",
    code: 2007,
    positionId: 3,
    teamId: 1,
    points: 69,
  },
  {
    name: "Oleksandr Zinchenko",
    code: 2008,
    positionId: 3,
    teamId: 1,
    points: 110,
  },
  {
    name: "William Saliba",
    code: 2009,
    positionId: 3,
    teamId: 1,
    points: 132,
  },
  {
    name: "Jakub Kiwior",
    code: 2010,
    positionId: 3,
    teamId: 1,
    points: 28,
  },
  {
    name: "Thomas Partey",
    code: 3001,
    positionId: 4,
    teamId: 1,
    points: 117,
  },
  {
    name: "Granit Xhaka",
    code: 3002,
    positionId: 5,
    teamId: 1,
    points: 193,
  },
  {
    name: "Mohamed Elneny",
    code: 3003,
    positionId: 4,
    teamId: 1,
    points: 19,
  },
  {
    name: "Bukayo Saka",
    code: 3004,
    positionId: 5,
    teamId: 1,
    points: 229,
  },
  {
    name: "Emile Smith Rowe",
    code: 3005,
    positionId: 5,
    teamId: 1,
    points: 20,
  },
  {
    name: "Martin Odegaard",
    code: 3006,
    positionId: 5,
    teamId: 1,
    points: 215,
  },
  {
    name: "Jorginho",
    code: 3007,
    positionId: 4,
    teamId: 1,
    points: 121,
  },
  {
    name: "Fabio Vieira",
    code: 3008,
    positionId: 5,
    teamId: 1,
    points: 89,
  },
  {
    name: "Reiss Nelson",
    code: 3009,
    positionId: 5,
    teamId: 1,
    points: 53,
  },
  {
    name: "Gabriel Martinelli",
    code: 4001,
    positionId: 6,
    teamId: 1,
    points: 217,
  },
  {
    name: "Edward Nketiah",
    code: 4002,
    positionId: 6,
    teamId: 1,
    points: 124,
  },
  {
    name: "Nicolas Pepe",
    code: 4003,
    positionId: 6,
    teamId: 1,
    points: 0,
  },
  {
    name: "Leandro Trossard",
    code: 4004,
    positionId: 6,
    teamId: 1,
    points: 170,
  },
  {
    name: "Gabriel Jesus",
    code: 4005,
    positionId: 6,
    teamId: 1,
    points: 157,
  },
  {
    name: "Kai Havertz",
    code: 4032,
    positionId: 6,
    teamId: 1,
    points: 164,
  },
  {
    name: "Emiliano Martinez",
    code: 1009,
    positionId: 1,
    teamId: 2,
    points: 165,
  },
  {
    name: "Robin Olsen",
    code: 1010,
    positionId: 1,
    teamId: 2,
    points: 10,
  },
  {
    name: "Calum Chambers",
    code: 2021,
    positionId: 3,
    teamId: 2,
    points: 22,
  },
  {
    name: "Tyrone Mings",
    code: 2022,
    positionId: 3,
    teamId: 2,
    points: 112,
  },
  {
    name: "Ezri Konsa",
    code: 2023,
    positionId: 3,
    teamId: 2,
    points: 111,
  },
  {
    name: "Kortney Hause",
    code: 2024,
    positionId: 3,
    teamId: 2,
    points: 0,
  },
  {
    name: "Matty Cash",
    code: 2025,
    positionId: 3,
    teamId: 2,
    points: 66,
  },
  {
    name: "Lucas Digne",
    code: 2026,
    positionId: 3,
    teamId: 2,
    points: 63,
  },
  {
    name: "Diego Carlos",
    code: 2027,
    positionId: 3,
    teamId: 2,
    points: 6,
  },
  {
    name: "Alex Moreno",
    code: 2028,
    positionId: 3,
    teamId: 2,
    points: 77,
  },
  {
    name: "Douglas Luiz",
    code: 3020,
    positionId: 5,
    teamId: 2,
    points: 151,
  },
  {
    name: "Marvelous Nakamba",
    code: 3021,
    positionId: 4,
    teamId: 2,
    points: 0,
  },
  {
    name: "John McGinn",
    code: 3022,
    positionId: 5,
    teamId: 2,
    points: 104,
  },
  {
    name: "Morgan Sanson",
    code: 3023,
    positionId: 5,
    teamId: 2,
    points: 9,
  },
  {
    name: "Jacob Ramsey",
    code: 3024,
    positionId: 5,
    teamId: 2,
    points: 132,
  },
  {
    name: "Emi Buendia",
    code: 3025,
    positionId: 5,
    teamId: 2,
    points: 127,
  },
  {
    name: "Leon Bailey",
    code: 3026,
    positionId: 5,
    teamId: 2,
    points: 111,
  },
  {
    name: "Tim Iroegbunam",
    code: 3027,
    positionId: 5,
    teamId: 2,
    points: 1,
  },
  {
    name: "Leander Dendoncker",
    code: 3028,
    positionId: 4,
    teamId: 2,
    points: 43,
  },
  {
    name: "Boubacar Kamara",
    code: 3029,
    positionId: 4,
    teamId: 2,
    points: 58,
  },
  {
    name: "Bertrand Traore",
    code: 4013,
    positionId: 6,
    teamId: 2,
    points: 19,
  },
  {
    name: "Ollie Watkins",
    code: 4014,
    positionId: 6,
    teamId: 2,
    points: 209,
  },
  {
    name: "Keinan Davis",
    code: 4015,
    positionId: 6,
    teamId: 2,
    points: 0,
  },
  {
    name: "Philippe Coutinho",
    code: 4016,
    positionId: 6,
    teamId: 2,
    points: 42,
  },
  {
    name: "Caleb Chukwuemeka",
    code: 4017,
    positionId: 6,
    teamId: 2,
    points: 0,
  },
  {
    name: "Cameron Archer",
    code: 4018,
    positionId: 6,
    teamId: 2,
    points: 7,
  },
  {
    name: "Jhon Duran",
    code: 4019,
    positionId: 6,
    teamId: 2,
    points: 11,
  },
  {
    name: "Darren Randolph",
    code: 1005,
    positionId: 1,
    teamId: 3,
    points: 0,
  },
  {
    name: "William Dennis",
    code: 1006,
    positionId: 1,
    teamId: 3,
    points: 0,
  },
  {
    name: "Mark Travers",
    code: 1007,
    positionId: 1,
    teamId: 3,
    points: 28,
  },
  {
    name: "Neto",
    code: 1008,
    positionId: 1,
    teamId: 3,
    points: 94,
  },
  {
    name: "Ryan Fredericks",
    code: 2011,
    positionId: 3,
    teamId: 3,
    points: 19,
  },
  {
    name: "Lloyd Kelly",
    code: 2012,
    positionId: 3,
    teamId: 3,
    points: 54,
  },
  {
    name: "Chris Mepham",
    code: 2013,
    positionId: 3,
    teamId: 3,
    points: 32,
  },
  {
    name: "Adam Smith",
    code: 2014,
    positionId: 3,
    teamId: 3,
    points: 63,
  },
  {
    name: "James Hill",
    code: 2015,
    positionId: 3,
    teamId: 3,
    points: 2,
  },
  {
    name: "Jordan Zemura",
    code: 2016,
    positionId: 3,
    teamId: 3,
    points: 47,
  },
  {
    name: "Marcos Senesi",
    code: 2017,
    positionId: 3,
    teamId: 3,
    points: 61,
  },
  {
    name: "Ben Greenwood",
    code: 2018,
    positionId: 3,
    teamId: 3,
    points: 0,
  },
  {
    name: "Owen Bevan",
    code: 2019,
    positionId: 3,
    teamId: 3,
    points: 1,
  },
  {
    name: "Ilya Zabarnyi",
    code: 2020,
    positionId: 3,
    teamId: 3,
    points: 9,
  },
  {
    name: "Lewis Cook",
    code: 3010,
    positionId: 5,
    teamId: 3,
    points: 66,
  },
  {
    name: "David Brooks",
    code: 3011,
    positionId: 5,
    teamId: 3,
    points: 9,
  },
  {
    name: "Ryan Christie",
    code: 3012,
    positionId: 5,
    teamId: 3,
    points: 89,
  },
  {
    name: "Ben Pearson",
    code: 3013,
    positionId: 5,
    teamId: 3,
    points: 14,
  },
  {
    name: "Gavin Kilkenny",
    code: 3014,
    positionId: 5,
    teamId: 3,
    points: 0,
  },
  {
    name: "Philip Billing",
    code: 3015,
    positionId: 5,
    teamId: 3,
    points: 124,
  },
  {
    name: "Siriki Dembele",
    code: 3016,
    positionId: 5,
    teamId: 3,
    points: 14,
  },
  {
    name: "Joe Rothwell",
    code: 3017,
    positionId: 5,
    teamId: 3,
    points: 48,
  },
  {
    name: "Marcus Tavernier",
    code: 3018,
    positionId: 5,
    teamId: 3,
    points: 92,
  },
  {
    name: "Dominic Sadi",
    code: 3019,
    positionId: 5,
    teamId: 3,
    points: 2,
  },
  {
    name: "Justin Kluivert",
    code: 3174,
    positionId: 5,
    teamId: 3,
    points: 0,
  },
  {
    name: "Dominic Solanke",
    code: 4006,
    positionId: 6,
    teamId: 3,
    points: 157,
  },
  {
    name: "Jamal Lowe",
    code: 4007,
    positionId: 6,
    teamId: 3,
    points: 14,
  },
  {
    name: "Kieffer Moore",
    code: 4008,
    positionId: 6,
    teamId: 3,
    points: 74,
  },
  {
    name: "Jaidon Anthony",
    code: 4009,
    positionId: 6,
    teamId: 3,
    points: 89,
  },
  {
    name: "Christian Saydee",
    code: 4010,
    positionId: 6,
    teamId: 3,
    points: 0,
  },
  {
    name: "Dango Ouattara",
    code: 4011,
    positionId: 6,
    teamId: 3,
    points: 62,
  },
  {
    name: "Antoine Semenyo",
    code: 4012,
    positionId: 6,
    teamId: 3,
    points: 20,
  },
  {
    name: "Hamed Junior Traore",
    code: 4120,
    positionId: 6,
    teamId: 3,
    points: 0,
  },
  {
    name: "David Raya",
    code: 1011,
    positionId: 1,
    teamId: 4,
    points: 172,
  },
  {
    name: "Thomas Strakosha",
    code: 1012,
    positionId: 1,
    teamId: 4,
    points: 11,
  },
  {
    name: "Mark Flekken",
    code: 1050,
    positionId: 1,
    teamId: 4,
    points: 0,
  },
  {
    name: "Ethan Pinnock",
    code: 2029,
    positionId: 3,
    teamId: 4,
    points: 114,
  },
  {
    name: "Mads Bech Sorensen",
    code: 2030,
    positionId: 3,
    teamId: 4,
    points: 22,
  },
  {
    name: "Charlie Goode",
    code: 2031,
    positionId: 3,
    teamId: 4,
    points: 0,
  },
  {
    name: "Rico Henry",
    code: 2032,
    positionId: 3,
    teamId: 4,
    points: 118,
  },
  {
    name: "Mads Roerslev Rasmussen",
    code: 2033,
    positionId: 3,
    teamId: 4,
    points: 63,
  },
  {
    name: "Fin Stevens",
    code: 2034,
    positionId: 3,
    teamId: 4,
    points: 7,
  },
  {
    name: "Kristoffer Ajer",
    code: 2035,
    positionId: 3,
    teamId: 4,
    points: 27,
  },
  {
    name: "Aaron Hickey",
    code: 2036,
    positionId: 3,
    teamId: 4,
    points: 50,
  },
  {
    name: "Ben Mee",
    code: 2037,
    positionId: 3,
    teamId: 4,
    points: 146,
  },
  {
    name: "Mathias Jorgensen",
    code: 2038,
    positionId: 3,
    teamId: 4,
    points: 49,
  },
  {
    name: "Mathias Jensen",
    code: 3030,
    positionId: 5,
    teamId: 4,
    points: 139,
  },
  {
    name: "Christian Norgaard",
    code: 3031,
    positionId: 5,
    teamId: 4,
    points: 73,
  },
  {
    name: "Shandon Baptiste",
    code: 3032,
    positionId: 5,
    teamId: 4,
    points: 41,
  },
  {
    name: "Josh Dasilva",
    code: 3033,
    positionId: 5,
    teamId: 4,
    points: 101,
  },
  {
    name: "Vitaly Janelt",
    code: 3034,
    positionId: 4,
    teamId: 4,
    points: 110,
  },
  {
    name: "Frank Onyeka",
    code: 3035,
    positionId: 5,
    teamId: 4,
    points: 54,
  },
  {
    name: "Keane Lewis Potter",
    code: 3036,
    positionId: 5,
    teamId: 4,
    points: 33,
  },
  {
    name: "Ryan Trevitt",
    code: 3037,
    positionId: 5,
    teamId: 4,
    points: 1,
  },
  {
    name: "Kevin Schade",
    code: 3175,
    positionId: 5,
    teamId: 4,
    points: 38,
  },
  {
    name: "Ivan Toney",
    code: 4020,
    positionId: 6,
    teamId: 4,
    points: 220,
  },
  {
    name: "Yoane Wissa",
    code: 4021,
    positionId: 6,
    teamId: 4,
    points: 116,
  },
  {
    name: "Sergio Canos",
    code: 4022,
    positionId: 6,
    teamId: 4,
    points: 6,
  },
  {
    name: "Bryan Mbeumo",
    code: 4023,
    positionId: 6,
    teamId: 4,
    points: 179,
  },
  {
    name: "Halil Dervisoglu",
    code: 4024,
    positionId: 6,
    teamId: 4,
    points: 5,
  },
  {
    name: "Mikkel Damsgaard",
    code: 4025,
    positionId: 6,
    teamId: 4,
    points: 47,
  },
  {
    name: "Robert Sanchez",
    code: 1013,
    positionId: 1,
    teamId: 5,
    points: 106,
  },
  {
    name: "Jason Steele",
    code: 1014,
    positionId: 1,
    teamId: 5,
    points: 106,
  },
  {
    name: "Lewis Dunk",
    code: 2039,
    positionId: 3,
    teamId: 5,
    points: 148,
  },
  {
    name: "Adam Webster",
    code: 2040,
    positionId: 3,
    teamId: 5,
    points: 104,
  },
  {
    name: "Joel Veltman",
    code: 2041,
    positionId: 3,
    teamId: 5,
    points: 109,
  },
  {
    name: "Tariq Lamptey",
    code: 2042,
    positionId: 3,
    teamId: 5,
    points: 72,
  },
  {
    name: "Pervis Estupinan",
    code: 2043,
    positionId: 3,
    teamId: 5,
    points: 149,
  },
  {
    name: "Ed Turns",
    code: 2044,
    positionId: 3,
    teamId: 5,
    points: 7,
  },
  {
    name: "Odel Offiah",
    code: 2045,
    positionId: 3,
    teamId: 5,
    points: 4,
  },
  {
    name: "Pascal Grob",
    code: 3038,
    positionId: 5,
    teamId: 5,
    points: 181,
  },
  {
    name: "Steven Alzate",
    code: 3039,
    positionId: 5,
    teamId: 5,
    points: 9,
  },
  {
    name: "Moises Caicedo",
    code: 3040,
    positionId: 4,
    teamId: 5,
    points: 106,
  },
  {
    name: "Solly March",
    code: 3041,
    positionId: 5,
    teamId: 5,
    points: 155,
  },
  {
    name: "Adam Lallana",
    code: 3043,
    positionId: 5,
    teamId: 5,
    points: 58,
  },
  {
    name: "Taylor Richards",
    code: 3044,
    positionId: 5,
    teamId: 5,
    points: 0,
  },
  {
    name: "Jeremy Sarmiento",
    code: 3045,
    positionId: 5,
    teamId: 5,
    points: 23,
  },
  {
    name: "Kaoru Mitoma",
    code: 3046,
    positionId: 5,
    teamId: 5,
    points: 179,
  },
  {
    name: "Andrew Moran",
    code: 3047,
    positionId: 5,
    teamId: 5,
    points: 3,
  },
  {
    name: "Cameron Peupion",
    code: 3048,
    positionId: 5,
    teamId: 5,
    points: 5,
  },
  {
    name: "Jack Hinchy",
    code: 3049,
    positionId: 5,
    teamId: 5,
    points: 1,
  },
  {
    name: "Billy Gilmour",
    code: 3050,
    positionId: 5,
    teamId: 5,
    points: 38,
  },
  {
    name: "Yasin Ayari",
    code: 3051,
    positionId: 5,
    teamId: 5,
    points: 5,
  },
  {
    name: "Facundo Buoananotte",
    code: 3052,
    positionId: 5,
    teamId: 5,
    points: 30,
  },
  {
    name: "James Milner",
    code: 3100,
    positionId: 5,
    teamId: 5,
    points: 68,
  },
  {
    name: "Mahmoud Dahoud",
    code: 3176,
    positionId: 5,
    teamId: 5,
    points: 0,
  },
  {
    name: "Aaron Connolly",
    code: 4026,
    positionId: 6,
    teamId: 5,
    points: 0,
  },
  {
    name: "Danny Welbeck",
    code: 4027,
    positionId: 6,
    teamId: 5,
    points: 130,
  },
  {
    name: "Evan Ferguson",
    code: 4028,
    positionId: 6,
    teamId: 5,
    points: 118,
  },
  {
    name: "Julio Enciso",
    code: 4029,
    positionId: 6,
    teamId: 5,
    points: 76,
  },
  {
    name: "Simon Adingra",
    code: 4030,
    positionId: 6,
    teamId: 5,
    points: 0,
  },
  {
    name: "Denis Undav",
    code: 4031,
    positionId: 6,
    teamId: 5,
    points: 88,
  },
  {
    name: "Joao Pedro",
    code: 4121,
    positionId: 6,
    teamId: 5,
    points: 0,
  },
  {
    name: "Arijanet Muric",
    code: 1052,
    positionId: 1,
    teamId: 6,
    points: 0,
  },
  {
    name: "Bailey Peacock-Farrell",
    code: 1053,
    positionId: 1,
    teamId: 6,
    points: 0,
  },
  {
    name: "Lawrence Vigouroux",
    code: 1054,
    positionId: 1,
    teamId: 6,
    points: 0,
  },
  {
    name: "Denis Franchi",
    code: 1055,
    positionId: 1,
    teamId: 6,
    points: 0,
  },
  {
    name: "Jordan Beyer",
    code: 2176,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Hjalmar Ekdal",
    code: 2177,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Ameen Al Dakhil",
    code: 2178,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Dara O'Shea",
    code: 2179,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "CJ Egan Riley",
    code: 2180,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Luke McNally",
    code: 2181,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Bobby Thomas",
    code: 2182,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Charlie Taylor",
    code: 2183,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Conner Roberts",
    code: 2184,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Vitinho",
    code: 2185,
    positionId: 3,
    teamId: 6,
    points: 0,
  },
  {
    name: "Jack Cork",
    code: 3179,
    positionId: 4,
    teamId: 6,
    points: 0,
  },
  {
    name: "Josh Brownhill",
    code: 3180,
    positionId: 5,
    teamId: 6,
    points: 0,
  },
  {
    name: "Josh Cullen",
    code: 3181,
    positionId: 5,
    teamId: 6,
    points: 0,
  },
  {
    name: "Samuel Bastien",
    code: 3182,
    positionId: 5,
    teamId: 6,
    points: 0,
  },
  {
    name: "Scott Twine",
    code: 3183,
    positionId: 5,
    teamId: 6,
    points: 0,
  },
  {
    name: "Johann Berg Gudmundsson",
    code: 3184,
    positionId: 5,
    teamId: 6,
    points: 0,
  },
  {
    name: "Anass Zaroury",
    code: 4124,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Darko Churlinov",
    code: 4125,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Dara Costelloe",
    code: 4126,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Benson Manuel Hedilazio",
    code: 4127,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Enock Agyei",
    code: 4128,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Wout Weghorst",
    code: 4129,
    positionId: 6,
    teamId: 6,
    points: 93,
  },
  {
    name: "Lyle Foster",
    code: 4130,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Michael Obafemi",
    code: 4131,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Jay Rodriguez",
    code: 4132,
    positionId: 6,
    teamId: 6,
    points: 0,
  },
  {
    name: "Kepa Arrizabalaga",
    code: 1015,
    positionId: 1,
    teamId: 7,
    points: 164,
  },
  {
    name: "Marcus Bettinelli",
    code: 1016,
    positionId: 1,
    teamId: 7,
    points: 0,
  },
  {
    name: "Gabriel Slonina",
    code: 1017,
    positionId: 1,
    teamId: 7,
    points: 0,
  },
  {
    name: "Marc Cucurella",
    code: 2046,
    positionId: 3,
    teamId: 7,
    points: 87,
  },
  {
    name: "Thiago Silva",
    code: 2047,
    positionId: 3,
    teamId: 7,
    points: 98,
  },
  {
    name: "Ben Chilwell",
    code: 2048,
    positionId: 3,
    teamId: 7,
    points: 97,
  },
  {
    name: "Reece James",
    code: 2049,
    positionId: 3,
    teamId: 7,
    points: 80,
  },
  {
    name: "Cesar Azpilicueta",
    code: 2050,
    positionId: 3,
    teamId: 7,
    points: 61,
  },
  {
    name: "Malang Sarr",
    code: 2051,
    positionId: 3,
    teamId: 7,
    points: 0,
  },
  {
    name: "Trevoh Chalobah",
    code: 2052,
    positionId: 3,
    teamId: 7,
    points: 66,
  },
  {
    name: "Baba Rahman",
    code: 2053,
    positionId: 3,
    teamId: 7,
    points: 0,
  },
  {
    name: "Wesley Fofana",
    code: 2054,
    positionId: 3,
    teamId: 7,
    points: 57,
  },
  {
    name: "Bashir Humphreys",
    code: 2055,
    positionId: 3,
    teamId: 7,
    points: -1,
  },
  {
    name: "Benoit Badiashile",
    code: 2056,
    positionId: 3,
    teamId: 7,
    points: 43,
  },
  {
    name: "Malo Gusto",
    code: 2057,
    positionId: 3,
    teamId: 7,
    points: 0,
  },
  {
    name: "Carney Chukwuemeka",
    code: 3053,
    positionId: 5,
    teamId: 7,
    points: 20,
  },
  {
    name: "Mason Mount",
    code: 3054,
    positionId: 5,
    teamId: 7,
    points: 105,
  },
  {
    name: "Mateo Kovacic",
    code: 3055,
    positionId: 5,
    teamId: 7,
    points: 85,
  },
  {
    name: "Ruben Loftus-Cheek",
    code: 3056,
    positionId: 5,
    teamId: 7,
    points: 68,
  },
  {
    name: "Conor Gallagher",
    code: 3057,
    positionId: 5,
    teamId: 7,
    points: 87,
  },
  {
    name: "Omari Giraud-Hutchinson",
    code: 3058,
    positionId: 5,
    teamId: 7,
    points: 3,
  },
  {
    name: "Enzo Fernandez",
    code: 3059,
    positionId: 4,
    teamId: 7,
    points: 55,
  },
  {
    name: "Callum Hudson-Odoi",
    code: 4033,
    positionId: 6,
    teamId: 7,
    points: 0,
  },
  {
    name: "Christian Pulisic",
    code: 4034,
    positionId: 6,
    teamId: 7,
    points: 59,
  },
  {
    name: "Raheem Sterling",
    code: 4035,
    positionId: 6,
    teamId: 7,
    points: 152,
  },
  {
    name: "Armando Broja",
    code: 4036,
    positionId: 6,
    teamId: 7,
    points: 31,
  },
  {
    name: "Pierre-Emerick Aubameyang",
    code: 4037,
    positionId: 6,
    teamId: 7,
    points: 60,
  },
  {
    name: "David Datro Fofana",
    code: 4038,
    positionId: 6,
    teamId: 7,
    points: 6,
  },
  {
    name: "Mykhailo Mudryk",
    code: 4039,
    positionId: 6,
    teamId: 7,
    points: 37,
  },
  {
    name: "Noni Madueke",
    code: 4040,
    positionId: 6,
    teamId: 7,
    points: 31,
  },
  {
    name: "Romelu Lukaku",
    code: 4119,
    positionId: 6,
    teamId: 7,
    points: 0,
  },
  {
    name: "Christopher Nkunku",
    code: 4122,
    positionId: 6,
    teamId: 7,
    points: 0,
  },
  {
    name: "Nicolas Jackson",
    code: 4123,
    positionId: 6,
    teamId: 7,
    points: 0,
  },
  {
    name: "Vicente Guaita",
    code: 1018,
    positionId: 1,
    teamId: 8,
    points: 105,
  },
  {
    name: "Remi Matthews",
    code: 1019,
    positionId: 1,
    teamId: 8,
    points: 0,
  },
  {
    name: "Sam Johnstone",
    code: 1020,
    positionId: 1,
    teamId: 8,
    points: 58,
  },
  {
    name: "Joe Whitworth",
    code: 1021,
    positionId: 1,
    teamId: 8,
    points: 3,
  },
  {
    name: "Nathan Ferguson",
    code: 2058,
    positionId: 3,
    teamId: 8,
    points: 0,
  },
  {
    name: "James Tomkins",
    code: 2059,
    positionId: 3,
    teamId: 8,
    points: 13,
  },
  {
    name: "Tyrick Mitchell",
    code: 2060,
    positionId: 3,
    teamId: 8,
    points: 104,
  },
  {
    name: "Joel Ward",
    code: 2061,
    positionId: 3,
    teamId: 8,
    points: 91,
  },
  {
    name: "Marc Guehi",
    code: 2062,
    positionId: 3,
    teamId: 8,
    points: 110,
  },
  {
    name: "Joachim Andersen",
    code: 2063,
    positionId: 3,
    teamId: 8,
    points: 82,
  },
  {
    name: "Nathaniel Clyne",
    code: 2064,
    positionId: 3,
    teamId: 8,
    points: 63,
  },
  {
    name: "Chris Richards",
    code: 2065,
    positionId: 3,
    teamId: 8,
    points: 20,
  },
  {
    name: "Jefferson Lerma",
    code: 2175,
    positionId: 3,
    teamId: 8,
    points: 107,
  },
  {
    name: "Jeffrey Schlupp",
    code: 3060,
    positionId: 5,
    teamId: 8,
    points: 98,
  },
  {
    name: "Jairo Riedewald",
    code: 3061,
    positionId: 4,
    teamId: 8,
    points: 8,
  },
  {
    name: "Will Hughes",
    code: 3062,
    positionId: 5,
    teamId: 8,
    points: 53,
  },
  {
    name: "Eberechi Eze",
    code: 3063,
    positionId: 5,
    teamId: 8,
    points: 151,
  },
  {
    name: "Cheick Doucoure",
    code: 3064,
    positionId: 4,
    teamId: 8,
    points: 85,
  },
  {
    name: "Malcom Ebiowei",
    code: 3065,
    positionId: 5,
    teamId: 8,
    points: 0,
  },
  {
    name: "Kaden Rodney",
    code: 3066,
    positionId: 5,
    teamId: 8,
    points: 3,
  },
  {
    name: "Killian Phillips",
    code: 3067,
    positionId: 5,
    teamId: 8,
    points: 3,
  },
  {
    name: "Naouirou Ahamada",
    code: 3068,
    positionId: 5,
    teamId: 8,
    points: 7,
  },
  {
    name: "Wilfried Zaha",
    code: 4041,
    positionId: 6,
    teamId: 8,
    points: 115,
  },
  {
    name: "Jean Philippe Mateta",
    code: 4042,
    positionId: 6,
    teamId: 8,
    points: 50,
  },
  {
    name: "Jordan Ayew",
    code: 4043,
    positionId: 6,
    teamId: 8,
    points: 133,
  },
  {
    name: "Odsonne Edouard",
    code: 4044,
    positionId: 6,
    teamId: 8,
    points: 118,
  },
  {
    name: "Luke Plange",
    code: 4045,
    positionId: 6,
    teamId: 8,
    points: 0,
  },
  {
    name: "Michael Olise",
    code: 4046,
    positionId: 6,
    teamId: 8,
    points: 151,
  },
  {
    name: "Jordan Pickford",
    code: 1022,
    positionId: 1,
    teamId: 9,
    points: 134,
  },
  {
    name: "Asmir Begovic",
    code: 1023,
    positionId: 1,
    teamId: 9,
    points: 16,
  },
  {
    name: "Michael Keane",
    code: 2066,
    positionId: 3,
    teamId: 9,
    points: 37,
  },
  {
    name: "Ben Godfrey",
    code: 2067,
    positionId: 3,
    teamId: 9,
    points: 20,
  },
  {
    name: "Mason Holgate",
    code: 2068,
    positionId: 3,
    teamId: 9,
    points: 12,
  },
  {
    name: "Jarrad Branthwaite",
    code: 2069,
    positionId: 3,
    teamId: 9,
    points: 0,
  },
  {
    name: "Seamus Coleman",
    code: 2070,
    positionId: 3,
    teamId: 9,
    points: 74,
  },
  {
    name: "Vitaliy Mykolenko",
    code: 2071,
    positionId: 3,
    teamId: 9,
    points: 74,
  },
  {
    name: "James Tarkowski",
    code: 2072,
    positionId: 3,
    teamId: 9,
    points: 99,
  },
  {
    name: "Nathan Patterson",
    code: 2073,
    positionId: 3,
    teamId: 9,
    points: 40,
  },
  {
    name: "Reece Welch",
    code: 2074,
    positionId: 3,
    teamId: 9,
    points: 4,
  },
  {
    name: "Abdoulaye Doucoure",
    code: 3069,
    positionId: 5,
    teamId: 9,
    points: 72,
  },
  {
    name: "Tom Davies",
    code: 3070,
    positionId: 5,
    teamId: 9,
    points: 26,
  },
  {
    name: "Dele Alli",
    code: 3071,
    positionId: 5,
    teamId: 9,
    points: 3,
  },
  {
    name: "Demarai Gray",
    code: 3072,
    positionId: 5,
    teamId: 9,
    points: 112,
  },
  {
    name: "Dwight McNeil",
    code: 3073,
    positionId: 5,
    teamId: 9,
    points: 126,
  },
  {
    name: "Lewis Warrington",
    code: 3074,
    positionId: 5,
    teamId: 9,
    points: 2,
  },
  {
    name: "Idrissa Gueye",
    code: 3075,
    positionId: 5,
    teamId: 9,
    points: 78,
  },
  {
    name: "James Garner",
    code: 3076,
    positionId: 4,
    teamId: 9,
    points: 30,
  },
  {
    name: "Isaac Price",
    code: 3077,
    positionId: 5,
    teamId: 9,
    points: 1,
  },
  {
    name: "Ellis Simms",
    code: 3078,
    positionId: 5,
    teamId: 9,
    points: 18,
  },
  {
    name: "Amadou Onana",
    code: 3079,
    positionId: 4,
    teamId: 9,
    points: 99,
  },
  {
    name: "Neal Maupay",
    code: 4047,
    positionId: 6,
    teamId: 9,
    points: 59,
  },
  {
    name: "Dominic Calvert-Lewin",
    code: 4048,
    positionId: 6,
    teamId: 9,
    points: 60,
  },
  {
    name: "Alex Iwobi",
    code: 4049,
    positionId: 6,
    teamId: 9,
    points: 155,
  },
  {
    name: "Stanley Mills",
    code: 4050,
    positionId: 6,
    teamId: 9,
    points: 2,
  },
  {
    name: "Thomas Cannon",
    code: 4051,
    positionId: 6,
    teamId: 9,
    points: 3,
  },
  {
    name: "Bernd Leno",
    code: 1024,
    positionId: 1,
    teamId: 10,
    points: 142,
  },
  {
    name: "Marek Rodak",
    code: 1025,
    positionId: 1,
    teamId: 10,
    points: 38,
  },
  {
    name: "Kenny Tete",
    code: 2075,
    positionId: 3,
    teamId: 10,
    points: 106,
  },
  {
    name: "Terence Kongolo",
    code: 2076,
    positionId: 3,
    teamId: 10,
    points: 0,
  },
  {
    name: "Tim Ream",
    code: 2077,
    positionId: 3,
    teamId: 10,
    points: 98,
  },
  {
    name: "Tosin Adarabioyo",
    code: 2078,
    positionId: 3,
    teamId: 10,
    points: 65,
  },
  {
    name: "Antonee Robinson",
    code: 2079,
    positionId: 3,
    teamId: 10,
    points: 99,
  },
  {
    name: "Kevin Mbabu",
    code: 2080,
    positionId: 3,
    teamId: 10,
    points: 7,
  },
  {
    name: "Terry Ablade",
    code: 2081,
    positionId: 3,
    teamId: 10,
    points: 1,
  },
  {
    name: "Harrison Reed",
    code: 3080,
    positionId: 5,
    teamId: 10,
    points: 117,
  },
  {
    name: "Neeskens Kebano",
    code: 3081,
    positionId: 5,
    teamId: 10,
    points: 44,
  },
  {
    name: "Harry Wilson",
    code: 3082,
    positionId: 5,
    teamId: 10,
    points: 87,
  },
  {
    name: "Tom Cairney",
    code: 3083,
    positionId: 5,
    teamId: 10,
    points: 79,
  },
  {
    name: "Anthony Knockaert",
    code: 3084,
    positionId: 5,
    teamId: 10,
    points: 0,
  },
  {
    name: "Tyrese Francois",
    code: 3085,
    positionId: 5,
    teamId: 10,
    points: 3,
  },
  {
    name: "Joao Palhinha",
    code: 3086,
    positionId: 4,
    teamId: 10,
    points: 113,
  },
  {
    name: "Sasa Lukic",
    code: 3087,
    positionId: 5,
    teamId: 10,
    points: 20,
  },
  {
    name: "Aleksandar Mitrovic",
    code: 4052,
    positionId: 6,
    teamId: 10,
    points: 134,
  },
  {
    name: "Bobby Reid",
    code: 4053,
    positionId: 6,
    teamId: 10,
    points: 115,
  },
  {
    name: "Rodrigo Muniz",
    code: 4054,
    positionId: 6,
    teamId: 10,
    points: 0,
  },
  {
    name: "Jay Stansfield",
    code: 4055,
    positionId: 6,
    teamId: 10,
    points: 8,
  },
  {
    name: "Luke Harris",
    code: 4056,
    positionId: 6,
    teamId: 10,
    points: 9,
  },
  {
    name: "Willian",
    code: 4057,
    positionId: 6,
    teamId: 10,
    points: 114,
  },
  {
    name: "Carlos Vinicius",
    code: 4058,
    positionId: 6,
    teamId: 10,
    points: 88,
  },
  {
    name: "Alisson Becker",
    code: 1031,
    positionId: 1,
    teamId: 11,
    points: 210,
  },
  {
    name: "Adrian",
    code: 1032,
    positionId: 1,
    teamId: 11,
    points: 1,
  },
  {
    name: "Caoimhin Kelleher",
    code: 1033,
    positionId: 1,
    teamId: 11,
    points: 33,
  },
  {
    name: "Virgil van Dijk",
    code: 2094,
    positionId: 3,
    teamId: 11,
    points: 146,
  },
  {
    name: "Ibrahima Konate",
    code: 2095,
    positionId: 3,
    teamId: 11,
    points: 66,
  },
  {
    name: "Joe Gomez",
    code: 2096,
    positionId: 3,
    teamId: 11,
    points: 93,
  },
  {
    name: "Kostas Tsimikas",
    code: 2097,
    positionId: 3,
    teamId: 11,
    points: 93,
  },
  {
    name: "Andrew Robertson",
    code: 2098,
    positionId: 3,
    teamId: 11,
    points: 138,
  },
  {
    name: "Joel Matip",
    code: 2099,
    positionId: 3,
    teamId: 11,
    points: 48,
  },
  {
    name: "Rhys Williams",
    code: 2100,
    positionId: 3,
    teamId: 11,
    points: 0,
  },
  {
    name: "Trent Arnold",
    code: 2101,
    positionId: 3,
    teamId: 11,
    points: 182,
  },
  {
    name: "James Norris",
    code: 2102,
    positionId: 3,
    teamId: 11,
    points: 0,
  },
  {
    name: "Jarell Quansah",
    code: 2103,
    positionId: 3,
    teamId: 11,
    points: 0,
  },
  {
    name: "Nathanial Phillips",
    code: 2104,
    positionId: 3,
    teamId: 11,
    points: 12,
  },
  {
    name: "Calvin Ramsay",
    code: 2105,
    positionId: 3,
    teamId: 11,
    points: 8,
  },
  {
    name: "Alexis Mac Allister",
    code: 3042,
    positionId: 5,
    teamId: 11,
    points: 164,
  },
  {
    name: "Fabinho",
    code: 3098,
    positionId: 4,
    teamId: 11,
    points: 122,
  },
  {
    name: "Thiago Alcantara",
    code: 3099,
    positionId: 5,
    teamId: 11,
    points: 62,
  },
  {
    name: "Jordan Henderson",
    code: 3101,
    positionId: 5,
    teamId: 11,
    points: 101,
  },
  {
    name: "Curtis Jones",
    code: 3102,
    positionId: 5,
    teamId: 11,
    points: 64,
  },
  {
    name: "Harvey Elliott",
    code: 3103,
    positionId: 5,
    teamId: 11,
    points: 124,
  },
  {
    name: "Tyler Morton",
    code: 3104,
    positionId: 5,
    teamId: 11,
    points: 0,
  },
  {
    name: "Max Woltman",
    code: 3105,
    positionId: 5,
    teamId: 11,
    points: 0,
  },
  {
    name: "Melkamu Frauendorf",
    code: 3106,
    positionId: 5,
    teamId: 11,
    points: 3,
  },
  {
    name: "Fabio Carvalho",
    code: 3107,
    positionId: 5,
    teamId: 11,
    points: 49,
  },
  {
    name: "Bobby Clark",
    code: 3108,
    positionId: 5,
    teamId: 11,
    points: 4,
  },
  {
    name: "Stefan Bajetic",
    code: 3109,
    positionId: 4,
    teamId: 11,
    points: 44,
  },
  {
    name: "Mohamed Salah",
    code: 4064,
    positionId: 6,
    teamId: 11,
    points: 322,
  },
  {
    name: "Diogo Jota",
    code: 4065,
    positionId: 6,
    teamId: 11,
    points: 114,
  },
  {
    name: "Luis Diaz",
    code: 4066,
    positionId: 6,
    teamId: 11,
    points: 80,
  },
  {
    name: "Kaide Gordon",
    code: 4067,
    positionId: 6,
    teamId: 11,
    points: 0,
  },
  {
    name: "Harvey Blair",
    code: 4068,
    positionId: 6,
    teamId: 11,
    points: 0,
  },
  {
    name: "Darwin Nunez",
    code: 4069,
    positionId: 6,
    teamId: 11,
    points: 172,
  },
  {
    name: "Layton Stewart",
    code: 4070,
    positionId: 6,
    teamId: 11,
    points: 3,
  },
  {
    name: "Ben Doak",
    code: 4071,
    positionId: 6,
    teamId: 11,
    points: 5,
  },
  {
    name: "Cody Gakpo",
    code: 4072,
    positionId: 6,
    teamId: 11,
    points: 113,
  },
  {
    name: "Jack Walton",
    code: 1056,
    positionId: 1,
    teamId: 12,
    points: 0,
  },
  {
    name: "Matt Macey",
    code: 1057,
    positionId: 1,
    teamId: 12,
    points: 0,
  },
  {
    name: "James Shea",
    code: 1058,
    positionId: 1,
    teamId: 12,
    points: 0,
  },
  {
    name: "Daniel Potts",
    code: 2186,
    positionId: 3,
    teamId: 12,
    points: 0,
  },
  {
    name: "Gabriel Osho",
    code: 2187,
    positionId: 3,
    teamId: 12,
    points: 0,
  },
  {
    name: "Amarii Bell",
    code: 2188,
    positionId: 3,
    teamId: 12,
    points: 0,
  },
  {
    name: "Reece Burke",
    code: 2189,
    positionId: 3,
    teamId: 12,
    points: 0,
  },
  {
    name: "Tom Lockyer",
    code: 2190,
    positionId: 3,
    teamId: 12,
    points: 0,
  },
  {
    name: "Pelly Ruddock Mpanzu",
    code: 3185,
    positionId: 4,
    teamId: 12,
    points: 0,
  },
  {
    name: "Glen Rea",
    code: 3186,
    positionId: 4,
    teamId: 12,
    points: 0,
  },
  {
    name: "Allan Campbell",
    code: 3187,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Jordan Clark",
    code: 3188,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Luke Berry",
    code: 3189,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Louie Watson",
    code: 3190,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Elliot Thorpe",
    code: 3191,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Alfie Doughty",
    code: 3192,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Luke Freeman",
    code: 3193,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Fred Onyedinma",
    code: 3194,
    positionId: 5,
    teamId: 12,
    points: 0,
  },
  {
    name: "Dion Pereira",
    code: 4133,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Chiedozie Ogbene",
    code: 4134,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Carlos Mendes",
    code: 4135,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "John McAtee",
    code: 4136,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Carlton Morris",
    code: 4137,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Elijah Adebayo",
    code: 4138,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Cauley Woodrow",
    code: 4139,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Admiral Muskew",
    code: 4140,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Joe Taylor",
    code: 4141,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Aribim Pepple",
    code: 4142,
    positionId: 6,
    teamId: 12,
    points: 0,
  },
  {
    name: "Ederson",
    code: 1034,
    positionId: 1,
    teamId: 13,
    points: 220,
  },
  {
    name: "Zackary Steffen",
    code: 1035,
    positionId: 1,
    teamId: 13,
    points: 0,
  },
  {
    name: "Scott Carson",
    code: 1036,
    positionId: 1,
    teamId: 13,
    points: 0,
  },
  {
    name: "Stefan Ortega",
    code: 1037,
    positionId: 1,
    teamId: 13,
    points: 83,
  },
  {
    name: "Kyle Walker",
    code: 2106,
    positionId: 3,
    teamId: 13,
    points: 124,
  },
  {
    name: "Ruben Dias",
    code: 2107,
    positionId: 3,
    teamId: 13,
    points: 171,
  },
  {
    name: "John Stones",
    code: 2108,
    positionId: 3,
    teamId: 13,
    points: 152,
  },
  {
    name: "Nathan Ake",
    code: 2109,
    positionId: 3,
    teamId: 13,
    points: 167,
  },
  {
    name: "Aymeric Laporte",
    code: 2110,
    positionId: 3,
    teamId: 13,
    points: 93,
  },
  {
    name: "Luke Mbete",
    code: 2111,
    positionId: 3,
    teamId: 13,
    points: 0,
  },
  {
    name: "Josh Wilson Esbrand",
    code: 2112,
    positionId: 3,
    teamId: 13,
    points: 6,
  },
  {
    name: "Finley Burns",
    code: 2113,
    positionId: 3,
    teamId: 13,
    points: 0,
  },
  {
    name: "Rico Lewis",
    code: 2114,
    positionId: 3,
    teamId: 13,
    points: 70,
  },
  {
    name: "Sergio Gomez",
    code: 2115,
    positionId: 3,
    teamId: 13,
    points: 64,
  },
  {
    name: "Manuel Akanji",
    code: 2116,
    positionId: 3,
    teamId: 13,
    points: 183,
  },
  {
    name: "Kalvin Phillips",
    code: 3110,
    positionId: 4,
    teamId: 13,
    points: 34,
  },
  {
    name: "Rodri",
    code: 3111,
    positionId: 4,
    teamId: 13,
    points: 201,
  },
  {
    name: "Kevin de Bruyne",
    code: 3112,
    positionId: 5,
    teamId: 13,
    points: 262,
  },
  {
    name: "Bernardo Silva",
    code: 3113,
    positionId: 5,
    teamId: 13,
    points: 180,
  },
  {
    name: "Cole Palmer",
    code: 3114,
    positionId: 5,
    teamId: 13,
    points: 48,
  },
  {
    name: "James McAtee",
    code: 3115,
    positionId: 5,
    teamId: 13,
    points: 0,
  },
  {
    name: "Maximo Perrone",
    code: 3116,
    positionId: 4,
    teamId: 13,
    points: 2,
  },
  {
    name: "Shea Charles",
    code: 3117,
    positionId: 5,
    teamId: 13,
    points: 1,
  },
  {
    name: "Riyad Mahrez",
    code: 4073,
    positionId: 6,
    teamId: 13,
    points: 222,
  },
  {
    name: "Liam Delap",
    code: 4074,
    positionId: 6,
    teamId: 13,
    points: 0,
  },
  {
    name: "Julian Alvarez",
    code: 4075,
    positionId: 6,
    teamId: 13,
    points: 187,
  },
  {
    name: "Erling Haaland",
    code: 4076,
    positionId: 6,
    teamId: 13,
    points: 428,
  },
  {
    name: "Phil Foden",
    code: 4077,
    positionId: 6,
    teamId: 13,
    points: 205,
  },
  {
    name: "Jack Grealish",
    code: 4078,
    positionId: 6,
    teamId: 13,
    points: 188,
  },
  {
    name: "David De Gea",
    code: 1038,
    positionId: 1,
    teamId: 14,
    points: 278,
  },
  {
    name: "Tom Heaton",
    code: 1039,
    positionId: 1,
    teamId: 14,
    points: 16,
  },
  {
    name: "Victor Lindelof",
    code: 2117,
    positionId: 3,
    teamId: 14,
    points: 112,
  },
  {
    name: "Eric Bailly",
    code: 2118,
    positionId: 3,
    teamId: 14,
    points: 0,
  },
  {
    name: "Harry Maguire",
    code: 2119,
    positionId: 3,
    teamId: 14,
    points: 62,
  },
  {
    name: "Raphael Varane",
    code: 2120,
    positionId: 3,
    teamId: 14,
    points: 116,
  },
  {
    name: "Diogo Dalot",
    code: 2121,
    positionId: 3,
    teamId: 14,
    points: 153,
  },
  {
    name: "Luke Shaw",
    code: 2122,
    positionId: 3,
    teamId: 14,
    points: 171,
  },
  {
    name: "Alex Telles",
    code: 2123,
    positionId: 3,
    teamId: 14,
    points: 0,
  },
  {
    name: "Aaron Wan-Bissaka",
    code: 2124,
    positionId: 3,
    teamId: 14,
    points: 125,
  },
  {
    name: "Brandon Williams",
    code: 2125,
    positionId: 3,
    teamId: 14,
    points: 1,
  },
  {
    name: "Tyrell Malacia",
    code: 2126,
    positionId: 3,
    teamId: 14,
    points: 120,
  },
  {
    name: "Lisandro Martinez",
    code: 2127,
    positionId: 3,
    teamId: 14,
    points: 154,
  },
  {
    name: "Fred",
    code: 3118,
    positionId: 5,
    teamId: 14,
    points: 137,
  },
  {
    name: "Bruno Fernandes",
    code: 3119,
    positionId: 5,
    teamId: 14,
    points: 273,
  },
  {
    name: "Scott McTominay",
    code: 3120,
    positionId: 4,
    teamId: 14,
    points: 87,
  },
  {
    name: "Hannibal Mejbri",
    code: 3121,
    positionId: 5,
    teamId: 14,
    points: 0,
  },
  {
    name: "Charlie Savage",
    code: 3122,
    positionId: 5,
    teamId: 14,
    points: 0,
  },
  {
    name: "Donny van de Beek",
    code: 3123,
    positionId: 5,
    teamId: 14,
    points: 17,
  },
  {
    name: "Christian Eriksen",
    code: 3124,
    positionId: 5,
    teamId: 14,
    points: 159,
  },
  {
    name: "Casemiro",
    code: 3125,
    positionId: 4,
    teamId: 14,
    points: 186,
  },
  {
    name: "Kobbie Mainoo",
    code: 3126,
    positionId: 5,
    teamId: 14,
    points: 5,
  },
  {
    name: "Facundo Pellistri",
    code: 3127,
    positionId: 5,
    teamId: 14,
    points: 14,
  },
  {
    name: "Jadon Sancho",
    code: 4079,
    positionId: 6,
    teamId: 14,
    points: 148,
  },
  {
    name: "Anthony Elanga",
    code: 4080,
    positionId: 6,
    teamId: 14,
    points: 46,
  },
  {
    name: "Amad Diallo",
    code: 4081,
    positionId: 6,
    teamId: 14,
    points: 0,
  },
  {
    name: "Marcus Rashford",
    code: 4082,
    positionId: 6,
    teamId: 14,
    points: 330,
  },
  {
    name: "Mason Greenwood",
    code: 4083,
    positionId: 6,
    teamId: 14,
    points: 0,
  },
  {
    name: "Anthony Martial",
    code: 4084,
    positionId: 6,
    teamId: 14,
    points: 119,
  },
  {
    name: "Shola Shoretire",
    code: 4085,
    positionId: 6,
    teamId: 14,
    points: 0,
  },
  {
    name: "Alejandro Garnacho",
    code: 4086,
    positionId: 6,
    teamId: 14,
    points: 88,
  },
  {
    name: "Antony",
    code: 4087,
    positionId: 6,
    teamId: 14,
    points: 163,
  },
  {
    name: "Charlie McNeill",
    code: 4088,
    positionId: 6,
    teamId: 14,
    points: 1,
  },
  {
    name: "Martin Dubravka",
    code: 1026,
    positionId: 1,
    teamId: 15,
    points: 18,
  },
  {
    name: "Karl Darlow",
    code: 1027,
    positionId: 1,
    teamId: 15,
    points: 3,
  },
  {
    name: "Mark Gillespie",
    code: 1028,
    positionId: 1,
    teamId: 15,
    points: 0,
  },
  {
    name: "Nick Pope",
    code: 1029,
    positionId: 1,
    teamId: 15,
    points: 231,
  },
  {
    name: "Loris Karius",
    code: 1030,
    positionId: 1,
    teamId: 15,
    points: 2,
  },
  {
    name: "Matt Targett",
    code: 2082,
    positionId: 3,
    teamId: 15,
    points: 44,
  },
  {
    name: "Dan Burn",
    code: 2083,
    positionId: 3,
    teamId: 15,
    points: 170,
  },
  {
    name: "Jamaal Lascelles",
    code: 2084,
    positionId: 3,
    teamId: 15,
    points: 23,
  },
  {
    name: "Fabian Schar",
    code: 2085,
    positionId: 3,
    teamId: 15,
    points: 168,
  },
  {
    name: "Jamal Lewis",
    code: 2086,
    positionId: 3,
    teamId: 15,
    points: 6,
  },
  {
    name: "Paul Dummett",
    code: 2087,
    positionId: 3,
    teamId: 15,
    points: 4,
  },
  {
    name: "Emil Krafth",
    code: 2088,
    positionId: 3,
    teamId: 15,
    points: 3,
  },
  {
    name: "Javier Manquillo",
    code: 2089,
    positionId: 3,
    teamId: 15,
    points: 11,
  },
  {
    name: "Matt Ritchie",
    code: 2090,
    positionId: 3,
    teamId: 15,
    points: 11,
  },
  {
    name: "Kieran Trippier",
    code: 2091,
    positionId: 3,
    teamId: 15,
    points: 212,
  },
  {
    name: "Harrison Ashby",
    code: 2092,
    positionId: 3,
    teamId: 15,
    points: 5,
  },
  {
    name: "Sven Botman",
    code: 2093,
    positionId: 3,
    teamId: 15,
    points: 147,
  },
  {
    name: "Joseph Willock",
    code: 3088,
    positionId: 5,
    teamId: 15,
    points: 140,
  },
  {
    name: "Sean Longstaff",
    code: 3089,
    positionId: 5,
    teamId: 15,
    points: 135,
  },
  {
    name: "Jeff Hendrick",
    code: 3090,
    positionId: 5,
    teamId: 15,
    points: 0,
  },
  {
    name: "Miguel Almiron",
    code: 3091,
    positionId: 5,
    teamId: 15,
    points: 175,
  },
  {
    name: "Bruno Guimaraes",
    code: 3092,
    positionId: 4,
    teamId: 15,
    points: 132,
  },
  {
    name: "Ryan Fraser",
    code: 3093,
    positionId: 5,
    teamId: 15,
    points: 12,
  },
  {
    name: "Jacob Murphy",
    code: 3094,
    positionId: 5,
    teamId: 15,
    points: 95,
  },
  {
    name: "Joelinton",
    code: 3095,
    positionId: 5,
    teamId: 15,
    points: 171,
  },
  {
    name: "Elliot Anderson",
    code: 3096,
    positionId: 5,
    teamId: 15,
    points: 42,
  },
  {
    name: "Lewis Miley",
    code: 3097,
    positionId: 5,
    teamId: 15,
    points: 1,
  },
  {
    name: "Yankuba Minteh",
    code: 3177,
    positionId: 5,
    teamId: 15,
    points: 0,
  },
  {
    name: "Callum Wilson",
    code: 4059,
    positionId: 6,
    teamId: 15,
    points: 192,
  },
  {
    name: "Santiago Munoz",
    code: 4060,
    positionId: 6,
    teamId: 15,
    points: 0,
  },
  {
    name: "Allan Saint-Maximin",
    code: 4061,
    positionId: 6,
    teamId: 15,
    points: 75,
  },
  {
    name: "Anthony Gordon",
    code: 4062,
    positionId: 6,
    teamId: 15,
    points: 79,
  },
  {
    name: "Alexander Isak",
    code: 4063,
    positionId: 6,
    teamId: 15,
    points: 117,
  },
  {
    name: "Dean Henderson",
    code: 1040,
    positionId: 1,
    teamId: 16,
    points: 97,
  },
  {
    name: "Ethan Horvath",
    code: 1041,
    positionId: 1,
    teamId: 16,
    points: 0,
  },
  {
    name: "Wayne Hennessey",
    code: 1042,
    positionId: 1,
    teamId: 16,
    points: 26,
  },
  {
    name: "Neco Williams",
    code: 2128,
    positionId: 3,
    teamId: 16,
    points: 67,
  },
  {
    name: "Willy Boly",
    code: 2129,
    positionId: 3,
    teamId: 16,
    points: 53,
  },
  {
    name: "Joe Worrall",
    code: 2130,
    positionId: 3,
    teamId: 16,
    points: 72,
  },
  {
    name: "Scott McKenna",
    code: 2131,
    positionId: 3,
    teamId: 16,
    points: 42,
  },
  {
    name: "Steve Cook",
    code: 2132,
    positionId: 3,
    teamId: 16,
    points: 16,
  },
  {
    name: "Loic Mbe Soh",
    code: 2133,
    positionId: 3,
    teamId: 16,
    points: 9,
  },
  {
    name: "Jonathan Panzo",
    code: 2134,
    positionId: 3,
    teamId: 16,
    points: 0,
  },
  {
    name: "Richie Laryea",
    code: 2135,
    positionId: 3,
    teamId: 16,
    points: 0,
  },
  {
    name: "Giulian Biancone",
    code: 2136,
    positionId: 3,
    teamId: 16,
    points: 9,
  },
  {
    name: "Moussa Niakhate",
    code: 2137,
    positionId: 3,
    teamId: 16,
    points: 25,
  },
  {
    name: "Omar Richards",
    code: 2138,
    positionId: 3,
    teamId: 16,
    points: 0,
  },
  {
    name: "Harry Toffolo",
    code: 2139,
    positionId: 3,
    teamId: 16,
    points: 31,
  },
  {
    name: "Aaron Donnelly",
    code: 2140,
    positionId: 3,
    teamId: 16,
    points: 7,
  },
  {
    name: "Serge Aurier",
    code: 2141,
    positionId: 3,
    teamId: 16,
    points: 71,
  },
  {
    name: "Felipe",
    code: 2142,
    positionId: 3,
    teamId: 16,
    points: 21,
  },
  {
    name: "Jonjo Shelvey",
    code: 3128,
    positionId: 5,
    teamId: 16,
    points: 22,
  },
  {
    name: "Morgan Gibbs-White",
    code: 3129,
    positionId: 5,
    teamId: 16,
    points: 142,
  },
  {
    name: "Ryan Yates",
    code: 3130,
    positionId: 5,
    teamId: 16,
    points: 86,
  },
  {
    name: "Braian Ojeda",
    code: 3131,
    positionId: 5,
    teamId: 16,
    points: 0,
  },
  {
    name: "Harry Arter",
    code: 3132,
    positionId: 5,
    teamId: 16,
    points: 0,
  },
  {
    name: "Cheikhou Kouyate",
    code: 3133,
    positionId: 4,
    teamId: 16,
    points: 42,
  },
  {
    name: "Brandon Aguilera",
    code: 3134,
    positionId: 5,
    teamId: 16,
    points: 0,
  },
  {
    name: "Lewis O'Brien",
    code: 3135,
    positionId: 5,
    teamId: 16,
    points: 35,
  },
  {
    name: "Orel Mangala",
    code: 3136,
    positionId: 5,
    teamId: 16,
    points: 69,
  },
  {
    name: "Remo Freuler",
    code: 3137,
    positionId: 5,
    teamId: 16,
    points: 78,
  },
  {
    name: "Oliver Hammond",
    code: 3138,
    positionId: 5,
    teamId: 16,
    points: 3,
  },
  {
    name: "Danilo",
    code: 3139,
    positionId: 4,
    teamId: 16,
    points: 52,
  },
  {
    name: "Gustavo Scarpa",
    code: 3140,
    positionId: 5,
    teamId: 16,
    points: 17,
  },
  {
    name: "Chris Wood",
    code: 4089,
    positionId: 6,
    teamId: 16,
    points: 76,
  },
  {
    name: "Alex Mighten",
    code: 4090,
    positionId: 6,
    teamId: 16,
    points: 5,
  },
  {
    name: "Taiwo Awoniyi",
    code: 4091,
    positionId: 6,
    teamId: 16,
    points: 124,
  },
  {
    name: "Sam Surridge",
    code: 4092,
    positionId: 6,
    teamId: 16,
    points: 47,
  },
  {
    name: "Brennan Johnson",
    code: 4093,
    positionId: 6,
    teamId: 16,
    points: 164,
  },
  {
    name: "Emmanuel Dennis",
    code: 4094,
    positionId: 6,
    teamId: 16,
    points: 59,
  },
  {
    name: "Dale Taylor",
    code: 4095,
    positionId: 6,
    teamId: 16,
    points: 1,
  },
  {
    name: "Detlef Esapa Osong",
    code: 4096,
    positionId: 6,
    teamId: 16,
    points: 1,
  },
  {
    name: "Wes Foderingham",
    code: 1059,
    positionId: 1,
    teamId: 17,
    points: 0,
  },
  {
    name: "Adam Davies",
    code: 1060,
    positionId: 1,
    teamId: 17,
    points: 0,
  },
  {
    name: "Jordan Amissah",
    code: 1061,
    positionId: 1,
    teamId: 17,
    points: 0,
  },
  {
    name: "Jake Eastwood",
    code: 1062,
    positionId: 1,
    teamId: 17,
    points: 0,
  },
  {
    name: "Anel Ahmedhodzic",
    code: 2191,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "John Egan",
    code: 2192,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Chris Basham",
    code: 2193,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Max Lowe",
    code: 2194,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Rhys Norrington Davies",
    code: 2195,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Jack Robinson",
    code: 2196,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Jayden Bogle",
    code: 2197,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "George Baldock",
    code: 2198,
    positionId: 3,
    teamId: 17,
    points: 0,
  },
  {
    name: "Sander Berge",
    code: 3195,
    positionId: 5,
    teamId: 17,
    points: 0,
  },
  {
    name: "Oliver Norwood",
    code: 3196,
    positionId: 5,
    teamId: 17,
    points: 0,
  },
  {
    name: "John Fleck",
    code: 3197,
    positionId: 5,
    teamId: 17,
    points: 0,
  },
  {
    name: "Ismaila Coulibaly",
    code: 3198,
    positionId: 5,
    teamId: 17,
    points: 0,
  },
  {
    name: "Ben Osborn",
    code: 3199,
    positionId: 5,
    teamId: 17,
    points: 0,
  },
  {
    name: "Iliman Ndiaye",
    code: 4143,
    positionId: 6,
    teamId: 17,
    points: 0,
  },
  {
    name: "Oliver McBurnie",
    code: 4144,
    positionId: 6,
    teamId: 17,
    points: 0,
  },
  {
    name: "Rhian Brewster",
    code: 4145,
    positionId: 6,
    teamId: 17,
    points: 0,
  },
  {
    name: "Daniel Jebbison",
    code: 4146,
    positionId: 6,
    teamId: 17,
    points: 0,
  },
  {
    name: "William Osula",
    code: 4147,
    positionId: 6,
    teamId: 17,
    points: 0,
  },
  {
    name: "Fraser Forster",
    code: 1043,
    positionId: 1,
    teamId: 18,
    points: 79,
  },
  {
    name: "Hugo Lloris",
    code: 1044,
    positionId: 1,
    teamId: 18,
    points: 115,
  },
  {
    name: "Guglielmo Vicario",
    code: 1051,
    positionId: 1,
    teamId: 18,
    points: 0,
  },
  {
    name: "Matt Doherty",
    code: 2143,
    positionId: 3,
    teamId: 18,
    points: 50,
  },
  {
    name: "Sergio Reguilon",
    code: 2144,
    positionId: 3,
    teamId: 18,
    points: 0,
  },
  {
    name: "Cristian Romero",
    code: 2145,
    positionId: 3,
    teamId: 18,
    points: 83,
  },
  {
    name: "Davinson Sanchez",
    code: 2146,
    positionId: 3,
    teamId: 18,
    points: 49,
  },
  {
    name: "Emerson Royal",
    code: 2147,
    positionId: 3,
    teamId: 18,
    points: 113,
  },
  {
    name: "Joe Rodon",
    code: 2148,
    positionId: 3,
    teamId: 18,
    points: 0,
  },
  {
    name: "Eric Dier",
    code: 2149,
    positionId: 3,
    teamId: 18,
    points: 117,
  },
  {
    name: "Japhet Tanganga",
    code: 2150,
    positionId: 3,
    teamId: 18,
    points: 21,
  },
  {
    name: "Ben Davies",
    code: 2151,
    positionId: 3,
    teamId: 18,
    points: 126,
  },
  {
    name: "Ryan Sessegnon",
    code: 2152,
    positionId: 3,
    teamId: 18,
    points: 58,
  },
  {
    name: "Djed Spence",
    code: 2153,
    positionId: 3,
    teamId: 18,
    points: 8,
  },
  {
    name: "Pierre Hojbjerg",
    code: 3141,
    positionId: 5,
    teamId: 18,
    points: 153,
  },
  {
    name: "Harry Winks",
    code: 3142,
    positionId: 5,
    teamId: 18,
    points: 0,
  },
  {
    name: "Oliver Skipp",
    code: 3143,
    positionId: 4,
    teamId: 18,
    points: 67,
  },
  {
    name: "Rodrigo Bentancur",
    code: 3144,
    positionId: 5,
    teamId: 18,
    points: 94,
  },
  {
    name: "Yves Bissouma",
    code: 3145,
    positionId: 5,
    teamId: 18,
    points: 40,
  },
  {
    name: "Ivan Perisic",
    code: 3146,
    positionId: 5,
    teamId: 18,
    points: 131,
  },
  {
    name: "Pape Matar Sarr",
    code: 3147,
    positionId: 5,
    teamId: 18,
    points: 25,
  },
  {
    name: "Alfie Devine",
    code: 3148,
    positionId: 5,
    teamId: 18,
    points: 1,
  },
  {
    name: "Matthew Craig",
    code: 3149,
    positionId: 5,
    teamId: 18,
    points: 1,
  },
  {
    name: "James Maddison",
    code: 3178,
    positionId: 5,
    teamId: 18,
    points: 131,
  },
  {
    name: "Richarlison",
    code: 4097,
    positionId: 6,
    teamId: 18,
    points: 95,
  },
  {
    name: "Son Heung-Min",
    code: 4098,
    positionId: 6,
    teamId: 18,
    points: 220,
  },
  {
    name: "Harry Kane",
    code: 4099,
    positionId: 6,
    teamId: 18,
    points: 313,
  },
  {
    name: "Dane Scarlett",
    code: 4100,
    positionId: 6,
    teamId: 18,
    points: 0,
  },
  {
    name: "Dejan Kulusevski",
    code: 4101,
    positionId: 6,
    teamId: 18,
    points: 119,
  },
  {
    name: "Bryan Gil",
    code: 4102,
    positionId: 6,
    teamId: 18,
    points: 21,
  },
  {
    name: "Lukasz Fabianski",
    code: 1048,
    positionId: 1,
    teamId: 19,
    points: 147,
  },
  {
    name: "Alphonse Areola",
    code: 1049,
    positionId: 1,
    teamId: 19,
    points: 98,
  },
  {
    name: "Aaron Cresswell",
    code: 2166,
    positionId: 3,
    teamId: 19,
    points: 119,
  },
  {
    name: "Kurt Zouma",
    code: 2167,
    positionId: 3,
    teamId: 19,
    points: 117,
  },
  {
    name: "Vladimir Coufal",
    code: 2168,
    positionId: 3,
    teamId: 19,
    points: 85,
  },
  {
    name: "Angelo Ogbonna",
    code: 2169,
    positionId: 3,
    teamId: 19,
    points: 96,
  },
  {
    name: "Ben Johnson",
    code: 2170,
    positionId: 3,
    teamId: 19,
    points: 96,
  },
  {
    name: "Jamal Baptiste",
    code: 2171,
    positionId: 3,
    teamId: 19,
    points: 0,
  },
  {
    name: "Nayef Aguerd",
    code: 2172,
    positionId: 3,
    teamId: 19,
    points: 103,
  },
  {
    name: "Thilo Kehrer",
    code: 2173,
    positionId: 3,
    teamId: 19,
    points: 98,
  },
  {
    name: "Emerson Palmieri",
    code: 2174,
    positionId: 3,
    teamId: 19,
    points: 92,
  },
  {
    name: "Pablo Fornals",
    code: 3159,
    positionId: 5,
    teamId: 19,
    points: 133,
  },
  {
    name: "Nikola Vlasic",
    code: 3160,
    positionId: 5,
    teamId: 19,
    points: 0,
  },
  {
    name: "Tomas Soucek",
    code: 3161,
    positionId: 4,
    teamId: 19,
    points: 154,
  },
  {
    name: "Declan Rice",
    code: 3162,
    positionId: 4,
    teamId: 19,
    points: 153,
  },
  {
    name: "Freddie Potts",
    code: 3163,
    positionId: 5,
    teamId: 19,
    points: 4,
  },
  {
    name: "Daniel Chesters",
    code: 3164,
    positionId: 5,
    teamId: 19,
    points: 0,
  },
  {
    name: "Flynn Downes",
    code: 3165,
    positionId: 5,
    teamId: 19,
    points: 64,
  },
  {
    name: "Conor Coventry",
    code: 3166,
    positionId: 4,
    teamId: 19,
    points: 15,
  },
  {
    name: "Lucas Paqueta",
    code: 3167,
    positionId: 5,
    teamId: 19,
    points: 137,
  },
  {
    name: "Oliver Scarles",
    code: 3168,
    positionId: 5,
    teamId: 19,
    points: 3,
  },
  {
    name: "Keenan Appiah-Forson",
    code: 3169,
    positionId: 5,
    teamId: 19,
    points: 2,
  },
  {
    name: "Kamarai Simon-Swyer",
    code: 3170,
    positionId: 5,
    teamId: 19,
    points: 1,
  },
  {
    name: "Kaelan Casey",
    code: 3171,
    positionId: 5,
    teamId: 19,
    points: 1,
  },
  {
    name: "Levi Laing",
    code: 3172,
    positionId: 5,
    teamId: 19,
    points: 2,
  },
  {
    name: "Danny Ings",
    code: 4112,
    positionId: 6,
    teamId: 19,
    points: 141,
  },
  {
    name: "Michail Antonio",
    code: 4113,
    positionId: 6,
    teamId: 19,
    points: 194,
  },
  {
    name: "Jarrod Bowen",
    code: 4114,
    positionId: 6,
    teamId: 19,
    points: 244,
  },
  {
    name: "Said Benrahma",
    code: 4115,
    positionId: 6,
    teamId: 19,
    points: 200,
  },
  {
    name: "Gianluca Scamacca",
    code: 4116,
    positionId: 6,
    teamId: 19,
    points: 103,
  },
  {
    name: "Maxwel Cornet",
    code: 4117,
    positionId: 6,
    teamId: 19,
    points: 45,
  },
  {
    name: "Divin Mubama",
    code: 4118,
    positionId: 6,
    teamId: 19,
    points: 14,
  },
  {
    name: "Daniel Bentley",
    code: 1045,
    positionId: 1,
    teamId: 20,
    points: 7,
  },
  {
    name: "Matija Sarkic",
    code: 1046,
    positionId: 1,
    teamId: 20,
    points: 15,
  },
  {
    name: "Jose Sa",
    code: 1047,
    positionId: 1,
    teamId: 20,
    points: 163,
  },
  {
    name: "Rayan Ait Nouri",
    code: 2154,
    positionId: 3,
    teamId: 20,
    points: 79,
  },
  {
    name: "Hugo Bueno",
    code: 2155,
    positionId: 3,
    teamId: 20,
    points: 56,
  },
  {
    name: "Jonny Castro Otto",
    code: 2156,
    positionId: 3,
    teamId: 20,
    points: 58,
  },
  {
    name: "Nelson Semedo",
    code: 2157,
    positionId: 3,
    teamId: 20,
    points: 92,
  },
  {
    name: "Nathan Collins",
    code: 2158,
    positionId: 3,
    teamId: 20,
    points: 61,
  },
  {
    name: "Craig Dawson",
    code: 2159,
    positionId: 3,
    teamId: 20,
    points: 99,
  },
  {
    name: "Toti Gomes",
    code: 2160,
    positionId: 3,
    teamId: 20,
    points: 48,
  },
  {
    name: "Ki-Jana Hoever",
    code: 2161,
    positionId: 3,
    teamId: 20,
    points: 0,
  },
  {
    name: "Max Kilman",
    code: 2162,
    positionId: 3,
    teamId: 20,
    points: 113,
  },
  {
    name: "Dexter Lembikisa",
    code: 2163,
    positionId: 3,
    teamId: 20,
    points: 5,
  },
  {
    name: "Yerson Mosquera",
    code: 2164,
    positionId: 3,
    teamId: 20,
    points: 0,
  },
  {
    name: "Conor Coady",
    code: 2165,
    positionId: 3,
    teamId: 20,
    points: 82,
  },
  {
    name: "Chem Campbell",
    code: 3150,
    positionId: 5,
    teamId: 20,
    points: 7,
  },
  {
    name: "Luke Cundle",
    code: 3151,
    positionId: 5,
    teamId: 20,
    points: 0,
  },
  {
    name: "Ruben Neves",
    code: 3152,
    positionId: 5,
    teamId: 20,
    points: 134,
  },
  {
    name: "Mario Lemina",
    code: 3153,
    positionId: 4,
    teamId: 20,
    points: 47,
  },
  {
    name: "Joseph Hodge",
    code: 3154,
    positionId: 4,
    teamId: 20,
    points: 13,
  },
  {
    name: "Joao Gomes",
    code: 3155,
    positionId: 5,
    teamId: 20,
    points: 25,
  },
  {
    name: "Matheus Nunes",
    code: 3156,
    positionId: 5,
    teamId: 20,
    points: 100,
  },
  {
    name: "Boubacar Traore",
    code: 3157,
    positionId: 4,
    teamId: 20,
    points: 21,
  },
  {
    name: "Chiquinho",
    code: 3158,
    positionId: 5,
    teamId: 20,
    points: 0,
  },
  {
    name: "Daniel Podence",
    code: 4103,
    positionId: 6,
    teamId: 20,
    points: 111,
  },
  {
    name: "Goncalo Guedes",
    code: 4104,
    positionId: 6,
    teamId: 20,
    points: 54,
  },
  {
    name: "Hee Chan Hwang",
    code: 4105,
    positionId: 6,
    teamId: 20,
    points: 89,
  },
  {
    name: "Raul Jimenez",
    code: 4106,
    positionId: 6,
    teamId: 20,
    points: 62,
  },
  {
    name: "Sasa Kalajdzic",
    code: 4107,
    positionId: 6,
    teamId: 20,
    points: 3,
  },
  {
    name: "Pedro Neto",
    code: 4108,
    positionId: 6,
    teamId: 20,
    points: 46,
  },
  {
    name: "Pablo Sarabia",
    code: 4109,
    positionId: 6,
    teamId: 20,
    points: 33,
  },
  {
    name: "Matheus Cunha",
    code: 4110,
    positionId: 6,
    teamId: 20,
    points: 64,
  },
  {
    name: "Fabio Silva",
    code: 4111,
    positionId: 6,
    teamId: 20,
    points: 0,
  },
];

const seedPlayers = async (prisma: any) => {
  console.log("seeding players");
  Promise.all(
    players.map(async (player) => {
      await prisma.player.upsert({
        where: { name: player.name },
        update: {
          name: player.name,
        },
        create: {
          name: player.name,
          positionId: player.positionId,
          teamId: player.teamId,
          code: player.code,
          points: player.points,
        },
      });
    })
  );
};

export { seedPlayers };
